0xsoniclabs/norma

Dockerfile, Makefile, go.mod, go.sum
This PR update `Dockerfile` and build process to allow for building multiple versions of the Sonic client. 
It parametrises the Dockerfile to checkout a specified version of Sonic client from git. It means that the client version from the `client/` directory is no more used. 
`Makefile` was updated to build Docker images from all Sonic tags we have at the moment. 
This is a first step to run various versions of the client in an experiment.  Next steps will be:
1. unlink the `client/` dir
2. extend scenario configuration to define an image
3. possibly make startup scripts also configurable to accomodate changes in start-up procedure of the client
=> opens possibility to build images of various Sonic versions

.gitmodules
This PR unlinks `client/` submodule from the project.
Norma is being updated to support multiple versions of the client running in the Norma network. To support this, the client will be checked out from its git repository and the client directory becomes redundant.
=> unlinks client submodule

driver/network.go, driver/node/opera.go, driver/norma/run.go, driver/parser/parser.go, driver/parser/parser_test.go, scenarios/test/baseline_check.yml
This PR allows for defining a list of network rules in scenario configuration. 
This is implemented as a free form key-value list to be easily extensible and it does not have to be touched to support additional rules in the future. 
The way of old configuration was removed, it was not used anyway.
=> allows for free-form network rules configuration

genesis/app/genesis.go, genesis/app/genesis_test.go, genesis/genesis/genesis.go, genesis/genesis/genesis_test.go, genesis/genesis/rules_config.go, genesis/genesis/rules_config_test.go
This PR allows for customising Network Rules in genesis file.
The rules are read from environment variables and updated in the genesis file generated by the CLI tool.
=> customise network rules

Dockerfile, driver/network/local/local_test.go, scripts/run_sonic_privatenet.sh
This PR extends testing to assess version of Sonic checked out from git. 
The version is stored in a file in the image and printed out when Sonic starts.
=> extends tests to test correct client version has started

driver/norma/run.go, driver/parser/parser.go, driver/parser/parser_test.go, scenarios/test/baseline_check.yml
This PR extends configuration of network rules. 
It splits definition to two sections: `genesis` and `updates`.
Genesis is applied to the genesis file when starting the nodes while updates contain changes in the rules during the network run.
=> updates network rules configuration to split to genesis and updates

driver/network/local/local.go, genesis/app/genesis.go, genesis/genesis/rules_config.go, genesis/genesis/rules_config_test.go, genesis/go.mod, genesis/go.sum, go.mod, go.sum
This PR updates dependencies to Sonic client to the recent main. 
It also removes the dependency to `opera.FakeNetRules` from the Norma main module.
=> updates dependencies to recent sonic main

driver/parser/parser.go, driver/parser/parser_test.go, scenarios/test/client_version_updates.yml, scenarios/test/nodes_start_stop.yml
This PR removes the `feature` construct from node configuration. It did nothing and was confusing that it actually does not configure anything. In particular, validator nodes are configured differently.
=> remove feature configuration from scenario node

genesis/genesis/genesis.go
This PR fixes adding of dynamic validators. 
It pre-allocates accounts for N validators that can be added during the network runtime.
=> fixes adding dynamic validators during network runtime

driver/monitoring/node_log_provider.go, driver/monitoring/node_log_provider_test.go
This PR simplifies code of `NodeLogParser`. It removes the internal list of `nodes` registered in this parser, as it was not used for any meaningful purpose.
=> removes unused nodes list

driver/rpc/rpc.go
This PR extends timeout to get transaction receipt. We had recently failing jenkins builds caused by timeouts. The timeout was increased 10times.
=> extends re-try mechanism for getting tx receipt

scenarios/test/min_base_fee_update.yml
this PR introduces a new scenario that updates `minBaseFee`.
It is supposed to test if this network rule does not cause network split when applied to old and a new client
=> introduces scenario to update min base fee

driver/executor/executor.go, driver/executor/executor_test.go, driver/parser/check.go, driver/parser/check_test.go, driver/parser/parser.go, driver/parser/parser_test.go, scenarios/test/advance_epoch.yml
- Parser now allow field `advance_epoch` of type `float32->int` (timing -> how many epoch to advance)
- Check now checks if timing is valid (not < 0 or > duration of scenario)
- Executor can now schedule Advance Epoch events by calling it on the network.
=> Executor and Parser now aware of advance epoch

genesis/genesis/rules_config.go, genesis/genesis/rules_config_test.go
To facilitate release testing scenarios, the following upgrade flag is required
https://github.com/0xsoniclabs/sonic/blob/3ecd7c5ad326c26fb97001b2bd3adcde5681a859/opera/rules.go#L243
This PR registers the flag into the rules and allow it to be enable/disabled by changing the network rules.
=> Register Upgrade.SingleProposerBlockFormation in rules

driver/parser/check_test.go, driver/parser/parser_test.go
This PR improves advance epoch test by:
- using inline error checking idioms
- remove redundant code by loop over scenarios
=> Improve advance epoch test

driver/network/backend.go, driver/network/epoch.go, driver/network/epoch_test.go, driver/network/local/local_test.go, driver/network/rules.go, driver/network/rules_test.go, driver/rpc/rpc.go
This PR updates the advance-epoch operation to block until the required epoch change has actually happened on the network.
The changes comprise the following steps:
- moved the `AdvanceEpoch` function from the `rules.go` file into its own `epochs.go` file
- extended `AdvanceEpoch` to wait for the network to have reached the new epoch
- added a log message after the epoch change listing the active validators for the new epoch
=> Make epoch advancement block until new epoch has been reached

driver/monitoring/app/app_source.go, driver/monitoring/node/node_source.go, driver/monitoring/node_log_provider.go, driver/monitoring/prom_log_provider.go, driver/monitoring/prometheus/prometheus.go, driver/monitoring/user/user_source.go, driver/network.go, driver/network/local/local.go, driver/network/local/local_test.go, driver/network/rpc/rpc_pool.go, driver/network_mock.go, driver/norma/progress.go, driver/norma/progress_test.go
This PR replaces the `AfterNodeRemoval` notification signal with a `BeforeNodeRemoval` signal.
All users of the `AfterNodeRemoval` event notification actually require to be informed about the removal of a node before it is actually removed to avoid attempting accessing its resources while it is removed.
Notifying interested parties only after the removal of a node may contribute to flakiness. Notifying nodes before they are removed may thus increase stability.
=> Signal removal of node before it is removed

driver/executor/executor.go, driver/network/local/local.go, driver/parser/check.go, driver/parser/check_test.go, driver/parser/parser.go, scenarios/scenario_test.go, scenarios/test/shutdown_initial_validator.yml
This PR introduces the support for a `end` field the configuration of validators used during network start-ups.
When configuring an initial validator to get offline at a given time, it is undelegating its stake and shutting down analog to what a dynamically introduced validator would do.
This extension facilitates the simulation of scenarios where the set of validators is fully exchanged over time.
=> Add support for shutting down initial validators

driver/checking/block_gas_rate.go
This PR increases the default `ceiling` value when checking block gas rate.
Current value is 30M, but there are some scenarios that exceed this limit without intending to use this check.
The new value default value is `math.MaxFloat64` and the scenario will specify the ceiling value when relevant.
=> Increase default block gas ceiling when checking block gas rate

driver/monitoring/utils/periodic_source.go, driver/network.go, driver/network/local/local.go, load/controller/controller.go
This PR modifies `load/controller`'s `GetReceivedTransactions()` method so that it checks if the network is empty.
If so, it returns an error that the `periodic_source` knows to catch and do nothing and not panic.
This solves the problem that currently, there's a timing between last node removal and monitoring shutdown that a periodic source could `ReadValue()`. When such a call happen, the monitor shutdown will fail, sometimes panic.
=> App controller checks if network has no node

driver/executor/executor.go
This PR fixes a  bug where `validator ID mismatched` when starting a validator node with `instances > 1`.
Example of symptoms:
```
19:50:58  [32mINFO [0m[07-22|12:50:58.019] Nodes: 7, epc/blk heights: [19/177 19/177 19/176 19/177 19/176 19/176 19/176], tx/s: [18.456375 18.487394 18.518518 18.518518 18.42546 18.42546 18.36394], txs: 11, gas: 1208411, blk processing: [6.385ms 4.964ms 5.207ms 4.574ms 4.664ms 5.758ms 6.268ms]
19:50:58  [32mINFO [0m[07-22|12:50:58.201] Completed registration of new validator node [32mvalidator_id[0m=6
19:50:58  [31mERROR[0m[07-22|12:50:58.202] event execution failed                   [31mtime[0m=142.1 [31mname[0m="[validator-C-1] Creating node" [31mevent_time[0m=140.0 [31merror[0m="validator ID mismatch: expected 7, got 6" …
```
=> Fix validator ID mismatched

driver/rpc/rpc.go, driver/rpc/rpc_test.go
This PR modifies `driver/rpc/rpc_test.go` so that it checks `Call` instead of `TransactionReceipt`. 
The reason `TransactionReceipt` is no longer used can be found here: https://github.com/0xsoniclabs/norma/pull/121.
=> Rpc_test now checks Call instead of TransactionReceipt

driver/rpc/rpc.go, driver/rpc/rpc_test.go
Updates the retrieval of receipts to accept receipts with log messages produced by older and newer geth versions.
=> Make retrieval of receipts with logs backward compatible
